# dataset preparation

In [7]:
from pandas import *
 
# reading CSV file
data = read_csv("/Users/mac/Desktop/AUGCN/pygcn/205_2_Northwind_video.csv")
 
# converting column data to list
AU1 = data['AU01_c'].tolist()
#AU1, AU2, AU4）mouth  AU10, AU12, AU14, AU15, AU17, and AU25
AU2=data['AU02_c'].tolist()

AU4=data['AU04_c'].tolist()

AU10=data['AU10_c'].tolist()
AU12=data['AU12_c'].tolist()
AU14=data['AU14_c'].tolist()

AU15=data['AU15_c'].tolist()
AU17=data['AU17_c'].tolist()
AU25=data['AU25_c'].tolist()
AU_lst=[AU1,AU2,AU4,AU10,AU12,AU14,AU15,AU17,AU25]

10,12,14,15,17,25



(10, 12, 14, 15, 17, 25)

In [8]:
len(AU_lst)

9

In [9]:
len(AU_lst)
def adj_matrix(first_AU,second_AU):
    AU1=first_AU
    AU4=second_AU

    AU1_AU4_joint_count = 50 # Number of instances where both AU1 and AU4 are present
    AU4_count = 200 # Number of instances where AU4 is present
    total_count = 1000 # Total number of instances in the dataset

    P_AU1_AU4 = AU1_AU4_joint_count / total_count
    P_AU4 = AU4_count / total_count
    P14=AU1_AU4_joint_count/AU4_count
    #P_AU1_given_AU4 = P_AU1_AU4 / P_AU4

In [10]:
lst=[]
for i in range(9):
    print(int(AU_lst[i][0]))
    lst.append(int(AU_lst[i][0]))

0
0
0
0
0
0
0
0
0


In [11]:
AU_set_lst=[]
for i in range(len(AU_lst[0])):
    set=[]
    for j in range(len(AU_lst)):
        set.append(AU_lst[j][i])
    AU_set_lst.append(set)
    


In [12]:
len(AU_set_lst)

1050

In [13]:
AU_set_lst[0]

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [14]:
len(AU_set_lst[0])

9

In [15]:
AU_set_lst

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0

In [30]:
len(AU_set_lst)

1050

In [33]:
cnt=0
for i in range(len(AU_set_lst)):
    if AU_set_lst[i][1]==0.0:
        cnt+=1
print(cnt)

1041


In [36]:
def adj_matrix(AU_inc1,AU_inc2,feature):
    cnt1=0
    cnt2=0
    cnt_joint=0

    
    

    for i in range(len(feature)):
        if  feature[i][AU_inc1]==1.0:
            cnt1+=1
        if  feature[i][AU_inc2]==1.0:
            cnt2+=1
        if  feature[i][AU_inc2]==1.0 and feature[i][AU_inc1]==1.0:
            cnt_joint+=1
    

    AU1_AU2_joint_count = cnt_joint # Number of instances where both AU1 and AU4 are present
    AU2_count = cnt2 # Number of instances where AU4 is present
    total_count = len(feature) # Total number of instances in the dataset

    P_AU1_AU2 = AU1_AU2_joint_count / total_count
    P_AU2 = AU2_count / total_count
    #P_AU1_given_AU2 = P_AU1_AU2 / P_AU2
    P12=AU1_AU2_joint_count/AU2_count
    print(AU1_AU2_joint_count,AU2_count)
    return P12

In [37]:
adj_matrix(1,2,AU_set_lst)

3 438


0.00684931506849315

In [44]:
from itertools import permutations 
  
# Get all permutations of length 2 
# and length 2 
perm = permutations([1, 2, 3,4,5,6,7,8,9], 2) 
  
# Print the obtained permutations 
for i in list(perm): 
    print (i) 
    

(1, 2)
(1, 3)
(1, 4)
(1, 5)
(1, 6)
(1, 7)
(1, 8)
(1, 9)
(2, 1)
(2, 3)
(2, 4)
(2, 5)
(2, 6)
(2, 7)
(2, 8)
(2, 9)
(3, 1)
(3, 2)
(3, 4)
(3, 5)
(3, 6)
(3, 7)
(3, 8)
(3, 9)
(4, 1)
(4, 2)
(4, 3)
(4, 5)
(4, 6)
(4, 7)
(4, 8)
(4, 9)
(5, 1)
(5, 2)
(5, 3)
(5, 4)
(5, 6)
(5, 7)
(5, 8)
(5, 9)
(6, 1)
(6, 2)
(6, 3)
(6, 4)
(6, 5)
(6, 7)
(6, 8)
(6, 9)
(7, 1)
(7, 2)
(7, 3)
(7, 4)
(7, 5)
(7, 6)
(7, 8)
(7, 9)
(8, 1)
(8, 2)
(8, 3)
(8, 4)
(8, 5)
(8, 6)
(8, 7)
(8, 9)
(9, 1)
(9, 2)
(9, 3)
(9, 4)
(9, 5)
(9, 6)
(9, 7)
(9, 8)


In [46]:
from itertools import permutations 
  
# Get all permutations of length 2 
# and length 2 
perm = permutations([1, 2, 3,4,5,6,7,8,9], 2) 
len(list(perm))

72

In [17]:
import torch
adj2=[0]*9
adj3=[]
for i in range(9):
    adj3.append(adj2)
adj_matrix=torch.LongTensor(adj3)

In [18]:
adj3

[[0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [19]:
adj_matrix.shape

torch.Size([9, 9])

In [20]:
import torch
AU_set_lst = torch.LongTensor(AU_set_lst)
#AU_set_lst = AU_set_lst.to(torch.float32)
embedding = torch.nn.Embedding(num_embeddings=9, embedding_dim=40)

<ipython-input-20-188793abbe27>:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  AU_set_lst = torch.LongTensor(AU_set_lst)


In [21]:
AU_set_lst[0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
feature_AU=embedding(AU_set_lst[0])

In [23]:
feature_AU.shape

torch.Size([9, 40])

In [24]:
feature_AU.shape

torch.Size([9, 40])

In [25]:
AU_set_lst.shape

torch.Size([1050, 9])

In [26]:
AU1_AU4_joint_count = 50 # Number of instances where both AU1 and AU4 are present
AU4_count = 200 # Number of instances where AU4 is present
total_count = 1000 # Total number of instances in the dataset

P_AU1_AU4 = AU1_AU4_joint_count / total_count
P_AU4 = AU4_count / total_count

P_AU1_given_AU4 = P_AU1_AU4 / P_AU4

In [27]:
adj

NameError: name 'adj' is not defined

In [ ]:
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/zhangsscc99/AU-GCN.git
git push -u origin main

In [ ]:
AU_set_lst

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 1, 1, 0],
        [0, 0, 0,  ..., 1, 1, 0],
        [0, 0, 0,  ..., 1, 1, 0]])

In [ ]:
import torch
import torch.nn as nn

# Define the embedding layer
embedding = nn.Embedding(num_embeddings=10, embedding_dim=5)

# Define input data as a batch of sequences
batch_data = torch.LongTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Pass the input data through the embedding layer
batch_embedded_data = embedding(batch_data)

print(batch_embedded_data.shape)

torch.Size([3, 3, 5])


In [ ]:
embedding(AU_set_lst)

tensor([[[-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         ...,
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973]],

        [[-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         ...,
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973]],

        [[-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         ...,
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
         [-0.7201, -1.1949,  0.1325, -1.5353,  0.2973],
  

In [ ]:
lst

[0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
import torch
embedding = torch.nn.Embedding(9, 32)
au_to_index = {'AU1': 0, 'AU2': 1, 'AU4': 2, 'AU10': 3, 'AU12': 4, 'AU14': 5, 'AU15': 6, 'AU17': 7, 'AU25': 8}
# Define the list of AU values
au_values = [0.0, 0.0, 0.79, 0.0, 0.0, 0.25, 1.22, 0.12, 0.0]

# Generate the node matrix by looking up the embedding vectors for each AU index and setting the corresponding value in the node matrix
node_matrix = torch.zeros(9, 32)
for au, value in zip(au_to_index.keys(), au_values):
    index = au_to_index[au]
    node_matrix[index, :] = embedding(torch.tensor([index]))
    node_matrix[index, -1] = value

In [ ]:
node_matrix

tensor([[ 1.4894,  0.5478, -0.6628,  0.1166,  0.9929, -1.1410,  0.5103, -0.1439,
         -0.1601,  1.1087, -0.1015, -1.9240,  0.7532, -0.0209, -0.6281,  0.3738,
         -0.5575,  0.0558,  0.9118,  0.8077,  0.6810,  0.6153,  1.4814,  1.1481,
         -1.0449, -1.4813, -0.4227, -0.9889, -0.8273, -1.1422, -0.7581,  0.0000],
        [ 1.1981, -0.3142,  0.7920,  1.0069, -0.9000,  0.5435,  1.0826,  0.6671,
         -0.7738, -2.2656,  0.8132,  1.5088, -1.9220, -0.2756,  0.8175,  1.7601,
         -0.3528,  1.1340, -1.3005, -0.4112, -2.0637,  0.1366, -0.3946, -1.5041,
          1.4152,  1.8790, -0.4060,  1.7835,  0.2007,  0.5881,  0.0706,  0.0000],
        [ 0.2119,  0.6377, -1.1720,  1.4514, -0.1603, -1.5523,  0.4586,  1.6835,
          0.3907,  0.1871,  0.5565,  0.8485, -0.4227,  0.5697,  0.2039, -1.8103,
          0.5620,  0.3106, -1.5824, -0.8244,  1.4043,  0.6600,  0.1818, -1.0577,
          1.1143,  0.3098,  0.6283, -0.5339,  0.8067, -0.2011, -0.4892,  0.7900],
        [-1.4534, -0.0186

In [ ]:
node_matrix.shape

torch.Size([9, 32])

In [ ]:
len(AU_lst[3])

1050

In [ ]:
res=10

In [ ]:
from pandas import *
 
# reading CSV file
data = read_csv("/Users/mac/Desktop/AUGCN/pygcn/205_2_Northwind_video.csv")
 
# converting column data to list
AU1 = data['AU01_r'].tolist()
#AU1, AU2, AU4）mouth  AU10, AU12, AU14, AU15, AU17, and AU25
AU2=data['AU02_r'].tolist()

AU4=data['AU04_r'].tolist()

AU10=data['AU10_r'].tolist()
AU12=data['AU12_r'].tolist()
AU14=data['AU14_r'].tolist()

AU15=data['AU15_r'].tolist()
AU17=data['AU17_r'].tolist()
AU25=data['AU25_r'].tolist()
AU_lst=[AU1,AU2,AU4,AU10,AU12,AU14,AU15,AU17,AU25]





# data loading

# Model

#### layers definition

In [ ]:
import math

import torch

from torch.nn.parameter import Parameter
from torch.nn.modules.module import Module


class GraphConvolution(Module):
    """
    Simple GCN layer, similar to https://arxiv.org/abs/1609.02907
    """

    def __init__(self, in_features, out_features, bias=True):
        super(GraphConvolution, self).__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weight = Parameter(torch.FloatTensor(in_features, out_features))
        if bias:
            self.bias = Parameter(torch.FloatTensor(out_features))
        else:
            self.register_parameter('bias', None)
        self.reset_parameters()

    def reset_parameters(self):
        stdv = 1. / math.sqrt(self.weight.size(1))
        self.weight.data.uniform_(-stdv, stdv)
        if self.bias is not None:
            self.bias.data.uniform_(-stdv, stdv)

    def forward(self, input, adj):
        support = torch.mm(input, self.weight)
        output = torch.spmm(adj, support)
        if self.bias is not None:
            return output + self.bias
        else:
            return output

    def __repr__(self):
        return self.__class__.__name__ + ' (' \
               + str(self.in_features) + ' -> ' \
               + str(self.out_features) + ')'


#### model define

In [ ]:
import torch.nn as nn
import torch.nn.functional as F
#from pygcn.layers import GraphConvolution


class GCN(nn.Module):
    def __init__(self, nfeat, nhid, nclass, dropout):
        super(GCN, self).__init__()

        self.gc1 = GraphConvolution(nfeat, nhid)
        self.gc2 = GraphConvolution(nhid, nclass)
        #self.gc2 = nn.Linear(nhid, 1)
        self.linear = nn.Linear(nclass, 1)

        self.dropout = dropout

    def forward(self, x, adj):
        x = F.relu(self.gc1(x, adj))
        x = F.dropout(x, self.dropout, training=self.training)
        x = self.gc2(x, adj)
        #return F.log_softmax(x, dim=1)
        return self.linear(x)

        #所以gcn确实是这样，只需要改一层就可以了，输出层就OK。一行行源码进行解构


: 

: 

## training step

In [ ]:
from __future__ import division
from __future__ import print_function

import time
import argparse
import numpy as np

import torch
import torch.nn.functional as F
import torch.optim as optim

## training settings

In [ ]:
# Training settings
parser = argparse.ArgumentParser()
parser.add_argument('--no-cuda', action='store_true', default=False,
                    help='Disables CUDA training.')
parser.add_argument('--fastmode', action='store_true', default=False,
                    help='Validate during training pass.')
parser.add_argument('--seed', type=int, default=42, help='Random seed.')
parser.add_argument('--epochs', type=int, default=10,
                    help='Number of epochs to train.')
parser.add_argument('--lr', type=float, default=0.01,
                    help='Initial learning rate.')
parser.add_argument('--weight_decay', type=float, default=5e-4,
                    help='Weight decay (L2 loss on parameters).')
parser.add_argument('--hidden', type=int, default=16,
                    help='Number of hidden units.')
parser.add_argument('--dropout', type=float, default=0.5,
                    help='Dropout rate (1 - keep probability).')

_StoreAction(option_strings=['--dropout'], dest='dropout', nargs=None, const=None, default=0.5, type=<class 'float'>, choices=None, help='Dropout rate (1 - keep probability).', metavar=None)

In [ ]:
import numpy as np
import scipy.sparse as sp
import torch


def encode_onehot(labels):
    classes = set(labels)
    classes_dict = {c: np.identity(len(classes))[i, :] for i, c in
                    enumerate(classes)}
    labels_onehot = np.array(list(map(classes_dict.get, labels)),
                             dtype=np.int32)
    return labels_onehot
    


def load_data(path="../data/cora/", dataset="cora"):
    """Load citation network dataset (cora only for now)"""
    print('Loading {} dataset...'.format(dataset))

    idx_features_labels = np.genfromtxt("{}{}.content".format(path, dataset),
                                        dtype=np.dtype(str))
    features = sp.csr_matrix(idx_features_labels[:, 1:-1], dtype=np.float32)
    labels = encode_onehot(idx_features_labels[:, -1])

    # build graph
    idx = np.array(idx_features_labels[:, 0], dtype=np.int32)
    idx_map = {j: i for i, j in enumerate(idx)}
    edges_unordered = np.genfromtxt("{}{}.cites".format(path, dataset),
                                    dtype=np.int32)
    edges = np.array(list(map(idx_map.get, edges_unordered.flatten())),
                     dtype=np.int32).reshape(edges_unordered.shape)
    adj = sp.coo_matrix((np.ones(edges.shape[0]), (edges[:, 0], edges[:, 1])),
                        shape=(labels.shape[0], labels.shape[0]),
                        dtype=np.float32)

    # build symmetric adjacency matrix
    adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj)

    features = normalize(features)
    adj = normalize(adj + sp.eye(adj.shape[0]))

    idx_train = range(140)
    idx_val = range(200, 500)
    idx_test = range(500, 1500)

    features = torch.FloatTensor(np.array(features.todense()))
    labels = torch.LongTensor(np.where(labels)[1])
    adj = sparse_mx_to_torch_sparse_tensor(adj)

    idx_train = torch.LongTensor(idx_train)
    idx_val = torch.LongTensor(idx_val)
    idx_test = torch.LongTensor(idx_test)

    return adj, features, labels, idx_train, idx_val, idx_test


def normalize(mx):
    """Row-normalize sparse matrix"""
    rowsum = np.array(mx.sum(1))
    r_inv = np.power(rowsum, -1).flatten()
    r_inv[np.isinf(r_inv)] = 0.
    r_mat_inv = sp.diags(r_inv)
    mx = r_mat_inv.dot(mx)
    return mx


def accuracy(output, labels):
    preds = output.max(1)[1].type_as(labels)
    correct = preds.eq(labels).double()
    correct = correct.sum()
    return correct / len(labels)


def sparse_mx_to_torch_sparse_tensor(sparse_mx):
    """Convert a scipy sparse matrix to a torch sparse tensor."""
    sparse_mx = sparse_mx.tocoo().astype(np.float32)
    indices = torch.from_numpy(
        np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.int64))
    values = torch.from_numpy(sparse_mx.data)
    shape = torch.Size(sparse_mx.shape)
    return torch.sparse.FloatTensor(indices, values, shape)


In [ ]:
import numpy as np
import scipy.sparse as sp
import torch

In [ ]:
adj, features, labels, idx_train, idx_val, idx_test = load_data()

Loading cora dataset...


In [ ]:
adj.shape

torch.Size([2708, 2708])

In [ ]:
features.shape

torch.Size([2708, 1433])

In [ ]:
labels.shape

torch.Size([2708])

In [ ]:
features[0]

tensor([0., 0., 0.,  ..., 0., 0., 0.])

In [ ]:
labels

tensor([5, 0, 6,  ..., 1, 3, 5])

In [ ]:
idx_test

tensor([ 500,  501,  502,  503,  504,  505,  506,  507,  508,  509,  510,  511,
         512,  513,  514,  515,  516,  517,  518,  519,  520,  521,  522,  523,
         524,  525,  526,  527,  528,  529,  530,  531,  532,  533,  534,  535,
         536,  537,  538,  539,  540,  541,  542,  543,  544,  545,  546,  547,
         548,  549,  550,  551,  552,  553,  554,  555,  556,  557,  558,  559,
         560,  561,  562,  563,  564,  565,  566,  567,  568,  569,  570,  571,
         572,  573,  574,  575,  576,  577,  578,  579,  580,  581,  582,  583,
         584,  585,  586,  587,  588,  589,  590,  591,  592,  593,  594,  595,
         596,  597,  598,  599,  600,  601,  602,  603,  604,  605,  606,  607,
         608,  609,  610,  611,  612,  613,  614,  615,  616,  617,  618,  619,
         620,  621,  622,  623,  624,  625,  626,  627,  628,  629,  630,  631,
         632,  633,  634,  635,  636,  637,  638,  639,  640,  641,  642,  643,
         644,  645,  646,  647,  648,  6

In [ ]:
labels.shape

torch.Size([2708])

In [ ]:
labels

tensor([5, 0, 6,  ..., 1, 3, 5])

In [ ]:
import torch
import torch.nn as nn

m = nn.LogSoftmax()
loss = nn.NLLLoss()

# input is of size N x C = 3 x 5
# this is FloatTensor containing probability for 
# each item in batch for each class
input = torch.randn(3, 5)

# target is LongTensor for index of true class for each item in batch
# each element in target has to have 0 <= value < C
target = torch.tensor([1, 0, 4])

# output is tensor of 0 dimension, i.e., scaler wrapped in tensor
output = loss(m(input), target)

<ipython-input-34-93cd53a16b7d>:17: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  output = loss(m(input), target)


In [ ]:
labels2=[1,2,3,4,5]

In [ ]:

labels2=np.where(labels2)

In [ ]:
labels2

(array([0, 1, 2, 3, 4]),)

In [ ]:
torch.LongTensor(labels2)

tensor([1, 2, 3, 4, 5])

In [ ]:
labels5=[[100]]*2708

In [ ]:
labels5

[[100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],
 [100],


In [ ]:
labels5=torch.LongTensor(labels5)

In [ ]:
labels5.shape

torch.Size([2708, 1])

In [ ]:
m(input)

<ipython-input-38-15e831192f2b>:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  m(input)


tensor([[-3.1872, -2.7663, -1.0673, -1.9977, -0.8765],
        [-1.0446, -2.1218, -1.8376, -1.5604, -1.8382],
        [-3.4920, -3.5837, -2.7102, -0.1993, -2.8827]])

In [ ]:
adj[0]

tensor(indices=tensor([[  0,   8,  14, 258, 435, 544]]),
       values=tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667]),
       size=(2708,), nnz=6, layout=torch.sparse_coo)

In [ ]:
features.shape

torch.Size([2708, 1433])

In [ ]:
idx_val

tensor([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
        214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
        228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
        242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
        256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269,
        270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283,
        284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297,
        298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
        312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
        326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339,
        340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353,
        354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367,
        368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 3

In [ ]:
features.shape

torch.Size([2708, 1433])

In [ ]:
labels=load_data()

Loading cora dataset...


In [ ]:
labels.shape

(2708, 7)